baseURL = 'https://www.oestermarken-odder.dk'
languageCode = 'da-dk'
defaultContentLanguage = 'da'
timeZone = 'Europe/Copenhagen'
title = 'Beboerforeningen Østermarken'
sectionPagesMenu = 'main'

[languages.da.params]
read_more_copy = "Læs mere"

[params]
date_format = ":date_full"
site_logo = "oestermarken_skyer.png"
background_color_class = "bg-dark-green"
featured_image_class = "cover bg-bottom"
cover_dimming_class = "bg-white-0"

[params.contact]
email = 'bestyrelsen@oestermarken-odder.dk'


[module]
[[module.imports]]
path = "github.com/martignoni/hugo-cloak-email"
[[module.imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = 'github.com/theNewDynamic/gohugo-theme-ananke/v2'
[[module.imports]]
path = "github.com/KKKZOZ/hugo-admonitions"


[caches]
[caches.images]
dir = ':cacheDir/images'